var cigarBrands = ["100% Dominican",
    "13 Cigars",
    "13th Floor",
    "1502",
    "1666",
    "1861",
    "1876 Reserve",
    "1881",
    "1888",
    "1898 Independencia",
    "2012 Limited Edition",
    "22N-83W",
    "262",
    "3 Reynas",
    "3x3",
    "420's",
    "4x4",
    "5 Vegas",
    "601 Serie",
    "7 Cigar",
    "708",
    "809",
    "829",
    "82nd Ave Tobacco & Pipe Ltd",
    "898 Collection",
    "A. Fernandez",
    "A. Flores (by Pinar del Rio)",
    "A. Pontillo",
    "A. Turrent",
    "A.J. Fernandez",
    "A.O.A.",
    "A/R (Armando Ramos)",
    "Abam",
    "Abanci",
    "Abarisco",
    "Abuelo",
    "ACID",
    "Action",
    "Adan y Eva",
    "Adante",
    "Adduci",
    "Adipati",
    "Adolphus",
    "Adrian's",
    "Aganorsa Leaf",
    "Aging Room (by Oliveros)",
    "Agio",
    "Aguila",
    "Aida",
    "AKA (American Kick Ass)",
    "Al Capone",
    "Alabao",
    "Alacranes",
    "Alameda",
    "Alamo (Finck)",
    "Albatros",
    "Albero",
    "Albion",
    "Alcazar",
    "Aldo",
    "Alec Bradley",
    "Alejandro Lopez",
    "Alfons Mayer",
    "Alhambra",
    "Aliados",
    "All Americas",
    "All In!",
    "Allegria!",
    "Alma Sweets",
    "Almirante",
    "Alonso Menendez",
    "Alta Gracia",
    "Alternativos",
    "Alteza",
    "Alvarez Lopez",
    "Alvaro",
    "Ambiente",
    "Ambos Mundos",
    "Ambrosia",
    "American Born Cubans",
    "American Eagles",
    "American Made",
    "American Stogies",
    "American Western",
    "Amerigo (Thompson)",
    "Amerino",
    "Amero",
    "Amilcar Perez Castro (APC)",
    "Amish",
    "Amoroso",
    "Ana de Nicaragua",
    "Anacaona",
    "Ancla y Cazador",
    "Andiamo",
    "Andros",
    "Andujar",
    "Andulleros",
    "Angelenos",
    "Angelina",
    "Angry Elf",
    "Anillo de Oro",
    "Anillo de Plata",
    "Anoranzas",
    "Antelo",
    "Antico Cubano",
    "Antillian",
    "Antonio Benitez",
    "Antonio Fermin",
    "Antonio Gimenez",
    "Antonio y Cleopatra",
    "Antonius",
    "Aqua D'T",
    "Aquarius",
    "AR (Augusto Reyes)",
    "Arabesque",
    "Arango",
    "Aravega",
    "Aray & Sons",
    "Arganese",
    "Argopuro",
    "Argyle",
    "Aristocratas",
    "Aristoff",
    "Arman",
    "Armando Ramos",
    "Arnold's",
    "Aromas de San Andrés",
    "Arsen",
    "Arte",
    "Arte Cubano",
    "Arthur Avenue",
    "Artorius",
    "Arturas Felipe",
    "Arturo Fuente",
    "Aruhiba",
    "Arzt de los Reyes",
    "As You Like It",
    "Ashé",
    "Ashford Bentley's",
    "Ashton",
    "Aspira",
    "Astral",
    "Asylum",
    "Atabey",
    "Atlas World Select (Corona Cigar Co.)",
    "Atocha",
    "Avalon",
    "Avante",
    "Avanti",
    "Ave Maria",
    "AVO",
    "Avocado",
    "Axis",
    "AZ",
    "Azon",
    "Babalu",
    "Baccarat",
    "Bacchus (Thompson)",
    "Back 9 Cigar Company",
    "Back Cedarap",
    "Backgammon",
    "Backwoods",
    "Bad Dog",
    "Bad Frog",
    "Bad to the Bone (Outlaw Cigars)",
    "Bagatelle (Thompson)",
    "Bahama Mamas",
    "Bahia",
    "Bahias",
    "Bahiba",
    "Baitoa",
    "Balboa",
    "Baldwin",
    "Balmoral",
    "Bances",
    "Bandidos",
    "Bang Bang",
    "Bar and Books",
    "Barlovento (Thompson)",
    "Baron Ullman",
    "Battleground",
    "Bautismo de Fuego",
    "Bauza",
    "Bayamo",
    "Bayuk",
    "BD",
    "Beethoven",
    "Beldina",
    "Beliceño",
    "Belinda",
    "Belinda (Cuban)",
    "Bella Costa",
    "Bella Torres",
    "Bellaterra Ranch",
    "Bello (Cuba Tobacco Cigar Co.)",
    "Belmondo (Thompson)",
    "Belmore",
    "Ben Bey",
    "Benavides",
    "Benchmade",
    "Benedit",
    "Ben-Hur",
    "Bentley",
    "Berger & Argenti",
    "Bering",
    "Bernie Parent",
    "Bert Sugar",
    "Besitos",
    "Best Buy",
    "BestCigarPrices.com",
    "BH Puros",
    "Biarritz",
    "Bidwell Blend",
    "Big Al's",
    "Big Butt",
    "Big City",
    "Big Dog",
    "Big Shots",
    "Bijao",
    "Biker Boy International",
    "Biker's Butt",
    "Black Cat",
    "Black Crown",
    "Black Hawk",
    "Black Patch",
    "Black Sheep",
    "Blackstone",
    "Blair",
    "Blanco y Woermann",
    "Blanton's",
    "Blarney Stone",
    "Blender's Gold",
    "Blue Banana",
    "Blue Haze",
    "Blue Label",
    "Blue Mountain",
    "Blue Ribbon Segundos by Drew Estate",
    "Blue Train",
    "Bluewater",
    "Bluntville",
    "Boardwalk",
    "Bobalu",
    "Boca Monte",
    "Bocanada",
    "Bock y Ca",
    "Bodyshot",
    "Bogar",
    "Bogey's Stogies",
    "Bohemia",
    "Bohio (Thompson)",
    "Bolero",
    "Bolivar",
    "Bolivar (Cuban)",
    "Bon Bon (Cuba Tobacco Cigar Co.)",
    "Bona Vita",
    "Bonaparte",
    "Bonita Smoke Shop",
    "Boquilla",
    "Boris 11",
    "Bossner",
    "Boston Cigar Factory",
    "BOTL",
    "Bottom Shelf",
    "Bow Tie",
    "Brahma",
    "Braniff",
    "Brasil Autenticos",
    "Bravados",
    "Bravo",
    "Bravo (Dom)",
    "Bravos",
    "Brazil Trüllerie",
    "Breton",
    "Breve",
    "Brick House",
    "Briones",
    "Brioso",
    "Brittania",
    "Brobergs",
    "Brocatus",
    "Brooklyn",
    "Brun del Re",
    "Bucanero",
    "Buckshot",
    "Buena Vista",
    "Bufido",
    "Bugatti (by Perdomo)",
    "Buho",
    "Bulldog",
    "Bulldog Replacements",
    "Bundle King",
    "Bundles",
    "Burma",
    "Buscal Buivl",
    "Bustillo",
    "Butera",
    "Byron",
    "C&C",
    "C&V",
    "C. E. Beck",
    "C.C.I. Royal Satin Selection",
    "C.E.O.",
    "C.Gars Ltd",
    "Cabaiguan",
    "Caballeros",
    "Cabanas",
    "Cabanas (Cuban)",
    "Cabanas y Carbajal",
    "Cabita",
    "Cabo Classic",
    "Cabo Rojo",
    "Cacique",
    "Cacique Miami",
    "Cadenza",
    "Calderilla",
    "Calibre 58",
    "Calixto Lopez",
    "Calixto Lopez (Nic)",
    "Calle 8 Ocho",
    "Calle Ocho",
    "Callisto",
    "Camacho",
    "Camaguey",
    "Cameroon Giants",
    "Cameroon Secrets",
    "Camine Pietro",
    "Camino Real (by Route 45)",
    "Caminr Pietro",
    "Cammarata",
    "Camos",
    "Campa",
    "Campesino",
    "Campo Verde",
    "Cana",
    "Canad",
    "Canaleños",
    "Canaria D'Oro",
    "Candela",
    "Candlelight",
    "Canela",
    "Canimao",
    "Canonero",
    "Cantero",
    "Canuco",
    "CAO",
    "Caoba",
    "Caonaba",
    "Caonao",
    "Capa Fina",
    "Capadoro",
    "Capadura",
    "Capas",
    "Capisce",
    "Capoeira",
    "Capote",
    "Capricho Cubano",
    "Captain Black",
    "Captaris",
    "Cara Mia",
    "Carbon Copy",
    "Carbonell",
    "Cardenas",
    "Carey's",
    "Caribbean",
    "Caribbean Dreams",
    "Caribbean Line",
    "Caribbean Rounds",
    "Caribe",
    "Caribes",
    "Caridad",
    "Carillon",
    "Carinos",
    "Carl Upmann",
    "Carlin",
    "Carlos III",
    "Carlos Oliva",
    "Carlos Torano",
    "Carlscorona",
    "Carmelo",
    "Carmen",
    "Carmine Pietro",
    "Carnero",
    "Carnival Havana",
    "Carolina Cigar Company",
    "Carrington",
    "Cartel Cigars",
    "Carvelas",
    "Casa Antero",
    "Casa Blanca",
    "Casa Buena",
    "Casa Copan",
    "Casa Cuba",
    "Casa Culinaria",
    "Casa de Alegria",
    "Casa de Garcia",
    "Casa de Montecristo",
    "Casa de Nicaragua",
    "Casa de Oro",
    "Casa de Ortez",
    "Casa de Torres",
    "Casa del Puro",
    "Casa Fernandez",
    "Casa Gomez",
    "Casa Magna",
    "Casa Marina",
    "Casa Miranda",
    "Casa Montez",
    "Casa Royale",
    "Casada",
    "Casillas",
    "Casino Club (Finck)",
    "Casino Gold",
    "Castano",
    "Castro",
    "Castro Brothers",
    "Cavana",
    "Cedar Joe",
    "Cedros",
    "Celestino Vega",
    "Central Cigars",
    "Cerdan",
    "C'est La Vie",
    "cez",
    "Cezar Bronner",
    "CF Dominicana",
    "CFO",
    "Chaba",
    "Chacaro Black Stallion",
    "Chairman's Choice",
    "Chamuco",
    "Charatan",
    "Charles Denby",
    "Charles Fairmorn",
    "Charles Parker",
    "Charles the Great (Finck)",
    "Chateau Real By Drew Estate",
    "Chavelo",
    "Chaveta",
    "Chavon (Thompson)",
    "Cheap Bastard",
    "Chess",
    "Chevere",
    "Chevere by Villiger Ireland",
    "Cheyenne",
    "Chico",
    "Chieftain's",
    "Chimera",
    "Chinchalero",
    "Chinnock Cellars",
    "Chisum",
    "Christian of Denmark",
    "Christo 1886",
    "Chubbys",
    "Cibao",
    "Ciboney",
    "Cicero",
    "Cielo",
    "Cienfuegos (DR)",
    "Cienfuegos (Reyes)",
    "Cifuentes",
    "Cifuentes (Cuban)",
    "Cigar (The Cigar)",
    "Cigar Compadres",
    "Cigar Express",
    "Cigar Factory - New Orleans",
    "Cigar Factory Outlet",
    "Cigar Family",
    "Cigar Hut",
    "Cigar King",
    "Cigar of the Gods",
    "Cigar One",
    "Cigar Pequeno",
    "Cigar Place",
    "Cigar Pride",
    "Cigar Station",
    "Cigar.com",
    "Cigar5packs.com",
    "Cigars ETC",
    "Cigars in the Keys",
    "Cigars International",
    "Cigars of Habanos",
    "Cigars Rolled by Cubans",
    "Cinchalero",
    "Cinco Estrellas",
    "Cinta Azul",
    "Cipriano",
    "Cirilo",
    "Cisso",
    "Claddagh Reserva",
    "Classic",
    "Classico de Continental",
    "CLE",
    "Clementine",
    "Clipper",
    "Clipper Gold Reserve",
    "Club Classis",
    "Club Havana (by Cubanissimo)",
    "Clubmaster",
    "Cocinero",
    "Cocoa",
    "Cohiba",
    "Cohiba (Cuban)",
    "Cojimar",
    "Colba 1492",
    "Colinas",
    "Colita",
    "Colón",
    "Columbo",
    "Columbus (Honduras)",
    "Columbus (Thompson)",
    "Commandante",
    "Compaenen",
    "Companion",
    "Competere",
    "Conch Republic",
    "Conchita de Zarate",
    "Condal",
    "Condega (Nicaragua Cigar Co.)",
    "Condega (Tabacalera Tropical)",
    "Conestoga",
    "Conga Caliente",
    "Connecticut Crazy",
    "Connoisseur Choice: Dominican",
    "Conquista (by Rocky Patel)",
    "Conquistador",
    "Constantin",
    "Constellation",
    "Consuegra",
    "Conuco",
    "Cool Cat",
    "Copa Havana",
    "Copacabana",
    "Copanecos",
    "Coppo",
    "Coral Reef",
    "Corazon (Davidoff)",
    "Cordoba & Morales",
    "Cordova",
    "Cornerstone",
    "Coroa Real",
    "Corola",
    "Corona Cigar",
    "Corps Diplomatique",
    "Correvon",
    "Cortez",
    "Cortez Cigars",
    "Cortina",
    "Cosechero (Thompson)",
    "Cosmo",
    "Cost Cutter (Corona Cigar Co.)",
    "Costa",
    "Costa Brava",
    "Costa Dorada",
    "Coticas",
    "Courvoiser",
    "Craftman's Bench",
    "Crate",
    "Credo",
    "Creme de Jamaica",
    "Cremo",
    "Cremosa Cubana",
    "Cremosa Cubanos",
    "Creole Cigar Factory",
    "Crispin Patiño",
    "Cristo Cubanos",
    "Crossfire",
    "Crown Classic",
    "Crown Fumas",
    "Crown Jewel (M. Misti)",
    "Crown Vintage",
    "Crown White Label",
    "Crowned Heads",
    "Cruz Real",
    "CSB",
    "CSX",
    "Cuaba",
    "Cu-Avana",
    "Cuba Aliados",
    "Cuba Caiman",
    "Cuba Libre",
    "Cuba Rica Tabacalera",
    "Cubadom",
    "Cuban Aristocrat",
    "Cuban Bullet",
    "Cuban Cigar Company",
    "Cuban Cigar Factory",
    "Cuban Cigars 2U",
    "Cuban Classic",
    "Cuban Coffee (Mike's Cigars)",
    "Cuban Crafters",
    "Cuban Delights",
    "Cuban Desire",
    "Cuban Diplomat",
    "Cuban Exile",
    "Cuban Heirloom",
    "Cuban Heirloom Sun grown",
    "Cuban Honeys",
    "Cuban Leaf",
    "Cuban Paradise",
    "Cuban Parejo",
    "Cuban Pleasures",
    "Cuban Rejects",
    "Cuban Rounds",
    "Cuban Sandwich",
    "Cuban Selection (by Kristoff)",
    "Cuban Stock",
    "Cuban Throwouts",
    "Cuban Twist",
    "Cubana Fina",
    "Cubana Real Semilla (by Esteban Carreras)",
    "Cubana Royale",
    "Cubana Select",
    "Cubanidad",
    "Cubanissimo",
    "Cubano Claro",
    "Cubano Especiales",
    "Cubanos",
    "Cubao (Philippines)",
    "Cuba's Famous Brands",
    "Cubatabaco",
    "Cubella",
    "Cubita",
    "Cubita Spanish Market",
    "Cucaracha",
    "Cuenca",
    "Cuesta Rey",
    "Cueto",
    "Cueto (Cuban)",
    "Cuevas",
    "Cuevas Habanos",
    "Cugine",
    "Cult",
    "Culture",
    "Cumbres de Puriscal",
    "Cumpay",
    "Cupey",
    "Cupido",
    "Curivari",
    "Cusano",
    "Cuvee",
    "CVM Cigars",
    "CyB (formerly Cuenca y Blanco)",
    "Cyrilla",
    "Czar",
    "D.P. Cigars (Digna Polanco)",
    "Da Vinci",
    "Dabos",
    "DaGars",
    "Dale Earnhardt Jr.",
    "Damn Good Dominicans",
    "Daniel Marshall",
    "Danli Reserve",
    "Danlys",
    "Dannemann",
    "Danson Clasico",
    "Dark Shark",
    "Davidoff",
    "Davidoff (Cuban)",
    "Davies",
    "DAWA",
    "DCO",
    "D'Crossier",
    "De Cossio",
    "De Diego",
    "De Grisogono",
    "De Heeren van Ruysd",
    "De Huifkar",
    "De Kayang",
    "De La Concha",
    "De Leon",
    "De Leon Cigars",
    "De Nobili",
    "De Olifant",
    "Dea",
    "Dean’s",
    "Dean's",
    "Decision",
    "Deco Drive",
    "Defiance",
    "Defiant",
    "Del Campo",
    "Del Paraiso",
    "Delectados",
    "Delicados",
    "Deliciosos",
    "Deluxe",
    "Denobili",
    "Deseo",
    "Deseo Sombrio",
    "Devil's Weed",
    "D'Fernandino",
    "Di Fazio",
    "Diablo",
    "Diamond Crown",
    "Diana Silvius",
    "Diego de Ocampo (Thompson)",
    "Diego Silang",
    "Diesel",
    "Diesel Unlimited",
    "Diferente",
    "Dignity",
    "Dimeola",
    "Diogenes Puentes",
    "Diplomaticos",
    "Discover 1492",
    "Djarum",
    "Doc Holliday",
    "Dog Walker",
    "Dolce Amaretto",
    "Dolce Vita",
    "Dom Quixote",
    "Domaine de Lavalette",
    "Domenico",
    "Domenico (Greece)",
    "Domeza",
    "Domingold",
    "Dominican",
    "Dominican 3rds",
    "Dominican Bundles",
    "Dominican Delicias",
    "Dominican Elites",
    "Dominican Especiale",
    "Dominican Estates",
    "Dominican Green Label",
    "Dominican Original",
    "Dominican Overruns",
    "Dominican Rejects",
    "Dominican Republic Gold",
    "Dominican Royale",
    "Dominican Santiago Selection",
    "Dominican Special Selection",
    "Dominican Specials",
    "Dominican Supreme",
    "Dominicana Superba",
    "Dominicano",
    "Dominique",
    "Domino Park",
    "Don Abram Harris",
    "Don Alberto",
    "Don Alfredo",
    "Don Alfredo (Cuban)",
    "Don Antonio",
    "Don Antonio (Germany)",
    "Don Antonio Pellegrino",
    "Don Armando",
    "Don Asa",
    "Don Barco",
    "Don Barreto",
    "Don Benigno",
    "Don Bernardo",
    "Don Bienve",
    "Don Brotto",
    "Don Cándido",
    "Don Capitano",
    "Don Carbone",
    "Don Casimiro Collection",
    "Don Cassieni",
    "Don Cesar",
    "Don Chango",
    "Don Chicho",
    "Don Chuchu (Thompson)",
    "Don Cicero",
    "Don Cirlio",
    "Don Collins",
    "Don Conti",
    "Don Corazza",
    "Don Corleone",
    "Don Diego",
    "Don Douglas",
    "Don Duarte",
    "Don Elias",
    "Don Elio's",
    "Don Elliot",
    "Don Ernesto",
    "Don Escobar",
    "Don Fano (Thompson)",
    "Don Fausto",
    "Don Felo",
    "Don Fernando",
    "Don Fife",
    "Don Fonso",
    "Don Francisco",
    "Don Gabriel",
    "Don Garcia",
    "Don Geronimo",
    "Don Gonzales",
    "Don Gonzalez",
    "Don Goyo",
    "Don Guillermo",
    "Don Horacio del Monte",
    "Don Jacinto",
    "Don Jose",
    "Don Jose Correa",
    "Don Juan (Costa Rica)",
    "Don Juan (Dominican)",
    "Don Juan (Guatemala)",
    "Don Juan (Nic)",
    "Don Juan Urquijo",
    "Don Julian",
    "Don Julio",
    "Don Kike",
    "Don Kiki",
    "Don L. & Ventura",
    "Don Lachos",
    "Don Lencho",
    "Don Leo",
    "Don Leon",
    "Don Leoncio",
    "Don Lino",
    "Don Longo",
    "Don Lucas",
    "Don Lugo (Thompson)",
    "Don Luis",
    "Don Macho",
    "Don Manolo",
    "Don Manuel",
    "Don Marcos",
    "Don Mariano",
    "Don Mateo",
    "Don Melo",
    "Don Miguel",
    "Don Nicolas",
    "Don Nobody (Corona Cigar Co.)",
    "Don Norberto",
    "Don Osvaldo",
    "Don Otilio",
    "Don Pablo",
    "Don Pacheco",
    "Don Pancho",
    "Don Pedro",
    "Don Pedro Ramos",
    "Don Pepe",
    "Don Pepin Garcia",
    "Don Porfirio",
    "Don Priamo",
    "Don Purito (by Cubanissimo)",
    "Don Quijote",
    "Don Quixote",
    "Don Rafael",
    "Don Ramon",
    "Don Ramos",
    "Don Rene",
    "Don Rene de Cuba",
    "Don Rex",
    "Don Rey",
    "Don Rigo",
    "Don Rios",
    "Don Rivera",
    "Don Rogue",
    "Don Ronaldo",
    "Don Rosa",
    "Don Rubio",
    "Don Sebastian",
    "Don Sergio Ramar",
    "Don Seville (Hon)",
    "Don Seville (Nic)",
    "Don Smith",
    "Don Tito",
    "Don Tomas",
    "Don Tuto",
    "Don Ursulo",
    "Don Vicente",
    "Don Yayo",
    "Don Yeyo",
    "Don Zamora",
    "Dona Elba",
    "Dona Ero",
    "Dona Flor",
    "Dona Ines",
    "Dona Lydia",
    "Dona Patricia",
    "Dos Amigos",
    "Dos Hombres",
    "Dos Reinas",
    "Dos Rios",
    "Double Happiness",
    "Doublegun",
    "Doubloons",
    "Dr. Funk",
    "Dreams",
    "Drew Estate",
    "Dry Slitz",
    "Duarte 1884",
    "Due Mundi",
    "Dulce Maria",
    "Dumante",
    "Dunhill",
    "Duque",
    "Durango",
    "Dutch Delites",
    "Dutch Masters",
    "Dutch Treats",
    "Duya",
    "DWT",
    "Dynamite",
    "Dynamite (by Cubanissimo)",
    "E. Zarzuela",
    "E.P. Carrillo",
    "East End Cigar Co.",
    "East India Trading Company (K. Hansotia)",
    "Eden",
    "Edgar",
    "Edmundo Dantes",
    "Ego",
    "EH Cigars (Edgar Hoill)",
    "Ejecutivos",
    "El Artista (Thompson)",
    "El Balserito",
    "El Baton",
    "El Beso",
    "El Bigote",
    "El Botin Dominicano",
    "El Camino Dominicano",
    "El Canelo",
    "El Cantillito",
    "El Capitan",
    "El Caudillo",
    "El Cauto Rojo",
    "El Che",
    "El Cobre (by Oliva)",
    "El Coloso",
    "El Coloso (Cuban)",
    "El Compa",
    "El Competidor",
    "El Cortesano",
    "El Corto Gordo",
    "El Coto",
    "El Credito",
    "El Cubano",
    "El Cuño",
    "El Diablo",
    "El Diamante",
    "El Dorado",
    "El Duque",
    "El Embargo Cigar Factory",
    "El Emperador",
    "El Faro",
    "El Faro (Thompson)",
    "El Fenicio",
    "El Fidel",
    "El Galan",
    "El Gaucho",
    "El Gladiator",
    "El Gordo",
    "El Gran Rey",
    "El Grande Miguel",
    "El Guajiro",
    "El Hippie",
    "El Incomparable (Texas Cigar Brothers)",
    "El Jefe (Cigars Cartel of America)",
    "El Kajibo",
    "El Laguito",
    "El Macco",
    "El Mejor",
    "El Mundo del Tabaco",
    "El Original",
    "El Paraiso",
    "El Patio",
    "El Primer Mundo",
    "El Producto",
    "El Rey de Florez",
    "El Rey de Prussia",
    "El Rey del Mundo",
    "El Rey del Mundo (Cuban)",
    "El Rico Habano",
    "El Sabinar",
    "El Sabor de Miami",
    "El Sarare",
    "El Serio",
    "El Sol",
    "El Sublimado (Texas Cigar Brothers)",
    "El Suelo",
    "El Sueno",
    "El Taino Cedar",
    "El Tiante",
    "El Titan de Bronze",
    "El Trelles",
    "El Triunfador (by Tatuaje)",
    "El Triunfo",
    "El Trofeo Habano",
    "El Unicorno",
    "El Verso",
    "Elegante",
    "Elegante'",
    "Elevation",
    "Elogio",
    "Embassy",
    "Emerson",
    "Emersonscigars.com",
    "Emigrante",
    "Emilio",
    "Emilio Reyes",
    "Emperor",
    "Empress of Cuba",
    "En el Punto",
    "Enanos",
    "Encanto",
    "Encore",
    "Entourage",
    "Entrepreneur",
    "Epernay",
    "Epicurian Cigars",
    "Equilibrium",
    "Equus",
    "Erez",
    "Eric Mellgren",
    "Erik",
    "Erte",
    "Escarabin",
    "Escudo Cubano",
    "Esencia",
    "Espada de Oro",
    "Espanola",
    "Especiales",
    "Esperanza",
    "Espinosa",
    "Espinosa y Ortega (EO brands)",
    "Esplendido",
    "ESQ",
    "Esse",
    "Est. 1844",
    "Estavan",
    "Estavan Cruz",
    "Esteban Carrera",
    "Esteban Carreras",
    "Esteli Overruns",
    "Esteli Ruiz",
    "Esteliano",
    "Estrella",
    "Estrella Blanca",
    "Etiqueta Azul",
    "Eureka",
    "Evel Knievel Signature Series",
    "Evelio",
    "Evermore",
    "Everyday Joe",
    "Evil Clown",
    "Evita",
    "Exactus",
    "Excaliber",
    "Excelsior",
    "Exclusive Cigars",
    "Exhibit",
    "Exile",
    "Express Imports",
    "Exquisito",
    "Ezra Zion",
    "F. D. Grave",
    "Factory Direct Bundles",
    "Factory Direct Nicaraguan",
    "Factory Fresh",
    "Factory Outlet",
    "Factory Straight",
    "Factory Throwouts",
    "Fair Exchange",
    "FAKE Cohiba - Mexican Variety",
    "Fake Cuban Cohiba",
    "Falsetto",
    "Falto",
    "Famous",
    "Fanning`s",
    "Farias",
    "Farmer's Select",
    "Farnam Drive",
    "Fatboy",
    "Father & Son Cigars",
    "Faux King Gold Label",
    "Faxas",
    "Fedelis",
    "Felipe Forza",
    "Felipe Gregorio",
    "Felungo",
    "Fernandez",
    "Fernando Leon (by La Aurora)",
    "FG 2009",
    "Fidalgro Negro",
    "Fidelis",
    "Fidel's",
    "Fields of Gold",
    "Fiero",
    "Fifth Centennial",
    "Fighting Cock (Nicaragua)",
    "Fighting Cock (Philippines)",
    "Figurado Reserve",
    "Figurados",
    "Filipinas",
    "Finck",
    "Fine Catch",
    "Finest Cuban Cigars",
    "Finnegan's Reserve",
    "First Lady of the World",
    "First Priming",
    "Fittipaldi",
    "Five Star",
    "Flamenco",
    "Flatbed Cigar Co.",
    "Fletcher Cigar Company",
    "Fleur de la Reine",
    "Flor Cubana",
    "Flor de A. Allones",
    "Flor de Amor",
    "Flor de Baloney",
    "Flor de Besana",
    "Flor de Camaguey",
    "Flor de Carbonell",
    "Flor de Cesar",
    "Flor de Cielo",
    "Flor de Consuegra",
    "Flor de Copan",
    "Flor de Dios",
    "Flor de Dominguez",
    "Flor de Farach",
    "Flor de Filipinas",
    "Flor de Flores",
    "Flor de Florez",
    "Flor de Gonzalez",
    "Flor de Honduras",
    "Flor de Jalapa",
    "Flor de Jardin (Texas Cigar Brothers)",
    "Flor de Java",
    "Flor de Jose",
    "Flor de la Isabela",
    "Flor de Lis (Thompson)",
    "Flor de Los Reyes",
    "Flor de Manila",
    "Flor de Mexico",
    "Flor de Murias",
    "Flor de Nicaragua",
    "Flor de Oliva",
    "Flor de Oro",
    "Flor de Selva",
    "Flor de Ybor City",
    "Flor del Aire",
    "Flor del Caribe",
    "Flor del Todo",
    "Flor Fina",
    "Flor Isla Habana",
    "Flor Real",
    "Floras",
    "Florentino",
    "Flores y Rodriguez (by PDR)",
    "Florida Queen",
    "Fogo",
    "Fonseca",
    "Fonseca (Cuban)",
    "Forcade & Son",
    "Fortuna de Honduras (Finck)",
    "Fortunado (Thompson)",
    "Fortunato",
    "Forty Creek",
    "Foundry",
    "Foyle",
    "FP",
    "Francisco de Miranda",
    "Franco",
    "Frank Herrera",
    "Frank Llaneza 1961",
    "Frank Vincent",
    "Frankenmuth Original Cigar Company",
    "Free Cuba",
    "Fresh Rolled",
    "Fuego de Dios",
    "Fuego de la Noche",
    "Fuego del Rey",
    "Fuentes Crucet",
    "Fuma Dominica Especial",
    "Fuma Suprema",
    "Fumadores",
    "Fundacion Ancestral",
    "Fundadores Jamaica",
    "Fürst Bismarck",
    "G&V Game",
    "G. De Graaff",
    "G.A.R. by George Rico",
    "G2",
    "Gabriela",
    "Galactico",
    "Galiano",
    "Gallardo",
    "Gambler",
    "Game Day",
    "Garcia y Vega",
    "Garo",
    "Gato",
    "Gaucho",
    "GB Naked",
    "GDW (Guillen Cigars)",
    "Geminis",
    "General Honduran",
    "Genuine",
    "Genuine Counterfeit",
    "Georges Reserve",
    "Gerant's",
    "Gérard Père et Fils",
    "Geronimo",
    "Giaconda",
    "Gil Gonzales Davila",
    "Gilbert de Montsalvat",
    "Gilberto Cubana",
    "Gilberto Oliva",
    "Gioconda",
    "Gispert",
    "Gispert (Cuban)",
    "Gloria de Leon",
    "Gloria Palmera",
    "God of Fire",
    "Gold Rush",
    "Golden Class (Felipe Gregorio)",
    "Golden Harvest",
    "Golden Sun",
    "Golfers' Choice",
    "Gonzalez Habano Co.",
    "Good Days Factory Rejects",
    "Good Times",
    "Gorilla Fingers",
    "Gourmet Dessert",
    "Governor's",
    "Goya",
    "GR Specials",
    "Grabs",
    "Gran Alfonso Cigars",
    "Gran Cantidad",
    "Gran Cuba",
    "Gran Habano",
    "Gran Havana",
    "Gran Vida by Rocky Patel",
    "Grand Cameroon",
    "Grand Maduro",
    "Grand Marnier",
    "Grand Nica",
    "Grand Virrey",
    "Grande",
    "Grandes de España",
    "Grass",
    "Graycliff",
    "Great (bleeping) Cigars (Factory Direct Cigars)",
    "Great Lakes Cigars",
    "Great Wall",
    "Griffin's",
    "Guajiro",
    "Guama",
    "Guantanamera",
    "Guantanamera (Cuban)",
    "Guaranteed Jamaica",
    "Guayacan",
    "Guglielmo Winery",
    "Guillermo Leon (by La Aurora)",
    "Gunslinger (Outlaw Cigars)",
    "Gurkha",
    "H M (Humberto Mendoza)",
    "H. Upmann",
    "H. Upmann (Cuban)",
    "Habana Cuba (Oliveros)",
    "Habana Delight",
    "Habana Gold",
    "Habana Leon",
    "Habana Port",
    "Habana Real",
    "Habana Treasure",
    "Habanera",
    "Habanera 78",
    "Habanero 87",
    "Habaneros",
    "Habanica",
    "Habanique",
    "Habano",
    "Habano Clasico",
    "Habano Primero",
    "Habanos",
    "Habanos (Cuban)",
    "Habanos del Eden",
    "Habanos Esplendidos",
    "Habanos Hatuey",
    "Habanos Puros",
    "Hacienda Rio",
    "Hajenius",
    "Hamiltons",
    "Hammer & Sickle",
    "Hampton Arms",
    "Handelsgold",
    "Happy Hour",
    "Harly",
    "Harrows",
    "Harvill",
    "Hasa Rey",
    "Hat's Off",
    "Hatuey",
    "Hauptmann's",
    "Havache",
    "Hav-a-Joe (Discontinued)",
    "Havana",
    "Havana Blend (Finck)",
    "Havana Cigar",
    "Havana Cigar Company",
    "Havana Cigars-Don Pedro Ramos",
    "Havana Classico",
    "Havana Cloud",
    "Havana Cognac",
    "Havana Cool",
    "Havana Cream",
    "Havana Dreams",
    "Havana Especial",
    "Havana Honeys",
    "Havana House",
    "Havana Humidor",
    "Havana Jim",
    "Havana Night Club",
    "Havana Originals",
    "Havana Republic",
    "Havana Soul",
    "Havana Star",
    "Havana Sun Grown",
    "Havana Sunrise",
    "Havana Sweets",
    "Havana Verde",
    "Hav-A-Tampa Jewel",
    "Hawk",
    "HE",
    "Headley Grange (by Crowned Heads)",
    "Heavenly",
    "Hecha Humo",
    "Hecho a Mano Dominicana",
    "Helix",
    "Hendrik Kelner",
    "Henri Poupart",
    "Henri Wintermans",
    "Henry Clay",
    "Henry George",
    "Herederos",
    "Heren van Ruysdeal",
    "Herfdog",
    "Herrera Esteli (by Drew Estate)",
    "Hesitant Pirate",
    "Hidalgo",
    "High Monk",
    "Highlander",
    "Hight",
    "Hirschsprung",
    "Hirsh & Garcia",
    "His Royal Majesty",
    "Hispaniola",
    "Hobo",
    "Hoboken Premium",
    "Hobson's Choice",
    "Hoffman House",
    "Hofnar",
    "Hoja Copan",
    "Hoja Cubana",
    "Hoja de Flores",
    "Hoja de Mexicali",
    "Hoja de Nicaragua",
    "Hoja de Oro",
    "Hoja Real",
    "Holt's",
    "Hombre de Oro",
    "Hommage 1492",
    "Honduran Cuban Tobaccos",
    "Honduran Estates",
    "Honduran Factory Corojos",
    "Honduran Gold",
    "Honduran Habano",
    "Honduran Overruns",
    "Honduras Caribbean",
    "Honduras Special",
    "Hookah",
    "Hopz (Ted's Cigars)",
    "Horsepower",
    "Hot Ash",
    "House of Cigars",
    "House of Dublin",
    "House of Gaspar",
    "House Resolution",
    "Hoya de Habano",
    "Hoyo de Casa",
    "Hoyo de Honduras",
    "Hoyo de Monterrey",
    "Hoyo de Monterrey (Cuban)",
    "Hugo Cassar",
    "Huifkar",
    "Hula Girls",
    "Humo Jaguar",
    "Humo Santo",
    "HuzGar",
    "HVC (by Casa Fernandez)",
    "i80",
    "Ibold",
    "Iguana (Thompson)",
    "Illuminati",
    "Illusione",
    "Imperio Cubano",
    "Inception",
    "Independencia",
    "Indian",
    "Indian Cha Cha Cha",
    "Indian Dominican",
    "Indian Fire",
    "Indian Head",
    "Indian Princess",
    "Indian Tabac",
    "Indiana Slims",
    "Indigo",
    "Industrial Press",
    "Inferno",
    "Infiesta",
    "Infiniti",
    "Inka Secret Blend (C.Gars Ltd.)",
    "Inmenso",
    "International",
    "International Cigar Factory Outlet",
    "ION",
    "Iracema",
    "Iron Horse",
    "Isabela",
    "Isabella",
    "Isla de Cuba",
    "Isla Rica",
    "Island",
    "Island Amaretto",
    "Island Blendz",
    "Island Cigar Factory",
    "Island Delights",
    "Islands",
    "Isleños",
    "ISOM",
    "Isthmus",
    "Iwan Ries & Co.",
    "J&D",
    "J&R Famous",
    "J. Cortes",
    "J. Fuego",
    "J. Grotto Series (Ocean State Cigars)",
    "J.L. Salazar y Hermanos",
    "J.R. Tobacco",
    "JAD",
    "Jade Cheroots",
    "Jaguar of Belize",
    "Jaime Garcia",
    "Jalopy",
    "Jamaica Bay",
    "Jamaica Heritage",
    "Jamaican Rounds",
    "Jamaican Vanilla",
    "James Norman",
    "Jameson",
    "Jamiaca Legacy",
    "Java (by Drew Estate)",
    "Javier Vizcaino",
    "JB Selection",
    "JC The Cuban Roller",
    "JD Cigars",
    "Jenuwine",
    "Jericho",
    "Jersey Joe's",
    "Jewels",
    "JF (Sri Lanka)",
    "JFC (Just for Catalogs)",
    "JFC Tobacco",
    "JFR (Just for Retailers)",
    "Jibaro",
    "Jimenez",
    "Jimmy Lakey's Cigar Company",
    "JML 1902",
    "JM's Dominican",
    "Joe's Reserve",
    "John Aylesbury",
    "John Bull",
    "John Hay",
    "John Starks",
    "John T's",
    "Jose Bartolo (Egypt)",
    "Jose Benito",
    "Jose Carlos",
    "Jose del Valle",
    "Jose Diamante",
    "Jose Dominguez (Palma)",
    "Jose Dominguez (Victor Sinclair)",
    "José Girbés",
    "Jose L. Piedra",
    "Jose Llopis",
    "Jose M. Losa (by La Tradicion Cubaba)",
    "Jose Marti",
    "Jose Paco",
    "Jose Ramon Villar",
    "Jose Seijas",
    "Josefina",
    "Journeys",
    "Joya Cubana",
    "Joya de Canarias",
    "Joya de Havana",
    "Joya de Honduras",
    "Joya de la Romana",
    "Joya de Nicaragua",
    "Joya del Cibao",
    "Joya del Jefe",
    "Joya del Rey",
    "Joya Real",
    "Joyas de Panama",
    "Joyitas",
    "Jpb",
    "JR",
    "JR Alternative",
    "JR Cuban Alternatives",
    "JR Edicion Limitada Alternative",
    "JR Special Jamaican",
    "JR Ultimate",
    "Juan Clemente",
    "Juan Guillermo de Robles",
    "Juan Lopez",
    "Juan Lopez (Cuban)",
    "Juan Manuel Torres",
    "Juan y Ramon",
    "Judges Cave",
    "Julia Marlowe",
    "Juneda",
    "Jungle Smokes",
    "Justus van Maurik",
    "JW",
    "k",
    "K. A. Kendall",
    "K. Hansotia",
    "Kahlua",
    "Kalibur",
    "Kangaroo Alley",
    "Karel van Susanten",
    "Kauai",
    "K-Cigars",
    "Keep Moving",
    "Kelner",
    "Kenners Keus",
    "Kensington",
    "Kentucky",
    "Kentucky Derby (Ted's Cigars)",
    "Kentucky Gentlemen",
    "Kentucky Moonshine",
    "Kevin Michaels",
    "Key West Cigar",
    "Key West Cigars",
    "Kick Ass Quality Cigars",
    "King Cobra",
    "King David",
    "King Dominican",
    "King Edward",
    "King Kong Specials",
    "King Richard",
    "Kingpin",
    "Kings",
    "Kings Club",
    "King's Court",
    "Kingston",
    "Kingstown",
    "Kinky Friedman",
    "Kinsella Fino",
    "Kiskeya",
    "Klafter's Limited Reserve",
    "Knockando",
    "Koala",
    "Kristian James",
    "Kristoff",
    "L. Lynn",
    "La Aroma de Cuba",
    "La Aurora",
    "La Avida",
    "La Belleza",
    "La Bestia",
    "La Bonita",
    "La Brisa",
    "La Campiña",
    "La Caoba",
    "La Capitana",
    "La Caridad del Cobre",
    "La Carolina",
    "La Casa Grande",
    "La Casita Criolla (by Tatuaje)",
    "La Casona",
    "La Casta",
    "La Caya",
    "La Cima",
    "La Corona",
    "La Corona (Cuban)",
    "La Cosecha",
    "La Cumanesa",
    "La Cuna",
    "La Diferencia Cubana",
    "La Diligencia",
    "La Diva",
    "La Dueña (Janny García)",
    "La Eminencia",
    "La Escepcion",
    "La Escepcion (Cuban)",
    "La Esencia del Vino",
    "La Estrella Cubana",
    "La Fabuloso",
    "La Fama",
    "La Famosa",
    "La Fendrich",
    "La Finca",
    "La Flor de Armando Mendez",
    "La Flor de Cano",
    "La Flor de Cano (Cuban)",
    "La Flor de el Cairo",
    "La Flor de Java",
    "La Flor de Murias",
    "La Flor de Rafael González Márquez",
    "La Flor de Ynclan",
    "La Flor Del Caney",
    "La Flor Del Caney (Cuban)",
    "La Flor del Teide",
    "La Flor Dominicana",
    "La Floridita",
    "La Fontana",
    "La Francesca",
    "La Galana",
    "La Garita",
    "La Gianna Havana",
    "La Gloria Cubana",
    "La Gloria Cubana (Cuban)",
    "La Gran Fuma",
    "La Habanera",
    "La Hara",
    "La Havanita Cigar Factory",
    "La Herencia Cubana",
    "La Herencia de Cuba",
    "La Hoja Fiesta",
    "La Hoja Selecta",
    "La Intimidad",
    "La Invicta",
    "La Isla",
    "La Joya Cubana",
    "La Joya de San Andres",
    "La Jugada (Formerly Flor de Esteli)",
    "La Liberate",
    "La Libertad (DR)",
    "La Libertad (Nic)",
    "La Liga",
    "La Luna",
    "La Luna de Santa Maria",
    "La Marinita",
    "La Maximiliana",
    "La Meridiana",
    "La Mezcla Cubana",
    "La Mia",
    "La Misión",
    "La Native",
    "La Nubia",
    "La O'Paree",
    "La Palina",
    "La Palma",
    "La Palma de Oro",
    "La Paloma (Thompson)",
    "La Pantera",
    "La Paz",
    "La Pefecta",
    "La Perla Habana",
    "La Plata",
    "La Primadora",
    "La Primera",
    "La Primorosa",
    "La Princesa de Cuba",
    "La Prueba",
    "La Real",
    "La Regenta",
    "La Regional",
    "La Reina",
    "La Reloba",
    "La Reserva",
    "La Restina",
    "La Ribera",
    "La Rica",
    "La Rica Hoya",
    "La Riqueza",
    "La Rosa",
    "La Rosa Especial",
    "La Sabana (Cuba Tobacco Cigar Co.)",
    "La Sabana (Nicaraguan)",
    "La Salle (Thompson)",
    "La Saola",
    "La Sirena",
    "La Surina",
    "La Tanita",
    "La Tradicion Cubana",
    "La Tribu",
    "La Unica",
    "La Veleza",
    "La Vencedora",
    "La Venga",
    "La Vida",
    "La Vieja Habana",
    "La Zona (Espinosa)",
    "Ladrillo",
    "Lady Club",
    "Lady Jane",
    "Lamb's Club (Finck)",
    "Lars Tetens",
    "Las Cabrillas",
    "Las Memorias Cubanas (by La Tradicion Cubana)",
    "Las Vegas",
    "Las Vegas Cigar Co.",
    "Lasandos",
    "L'Atelier",
    "Latin Gold",
    "Latin Quarter House of Cigars",
    "L'Attitude 18",
    "Laura Chavin",
    "Laurato",
    "Le Bonne Cigare",
    "Le Cigar",
    "Le Gran Fuma",
    "Le Hoyo",
    "Legacy",
    "Legado de Pepin",
    "LegendArio (by Camacho)",
    "Legion",
    "Leite & Alves",
    "Lempira",
    "Leon (Nicaragua)",
    "Leon (USA)",
    "Leon Jimenes",
    "Leonel",
    "Leopoldo",
    "Leprechaun",
    "Leuzzi Fumar",
    "Lew's Smokers",
    "Lex12",
    "Leyenda",
    "Lianos Dos Palmas",
    "Licenciados",
    "Liga IV",
    "Little Big Man",
    "Little Cigar Factory",
    "Little Havana",
    "Little Havana Cigars",
    "Litto Gomez Diez",
    "Live",
    "Loaiza uNo",
    "Lochem",
    "Lone Wolf",
    "Long Island",
    "Longchamp (France)",
    "Loose Cannon",
    "Lopez Tonight",
    "Lord Beaconsfield",
    "Lord Blackburn",
    "Lord Clinton",
    "Lord Tom",
    "Los Blancos",
    "Los Caleros",
    "Los Classicos Rejects",
    "Los Hermanos",
    "Los Imperialistas",
    "Los Libertadores",
    "Los Libertados",
    "Los Nicas",
    "Los Nietos Cigars",
    "Los Patriotas",
    "Los Perez",
    "Los Reyes Unidos",
    "Los Statos",
    "Lotar",
    "Lou Rodriguez",
    "Low Ball Louie's",
    "Lucas Santana",
    "Lucero",
    "Lucky 8",
    "Lucky Dublin",
    "Luis Alejandro",
    "Luis Gonzaga",
    "Luis Martinez",
    "Luna Azul",
    "Luna/Laissez-Faire",
    "Lusitania",
    "M&R",
    "M. J. Frias",
    "M.A.C.",
    "M.C.",
    "M.P.",
    "M3",
    "Macabi",
    "Macanudo",
    "Macarena",
    "MacBeth",
    "Macuro",
    "Mad Dog Cigars",
    "Madison",
    "Madrigal Habana",
    "Maestro Cubano",
    "Magellan",
    "Magicos Cubanos",
    "Magna Carta",
    "Magnate",
    "Magnum Force",
    "Magus",
    "Maker's Choice",
    "Maker's Mark (Ted's Cigars)",
    "Malaguena",
    "Mama Rosa",
    "Mambo Sabroso",
    "Man",
    "Man O' War",
    "Mandalay",
    "Manifiesto",
    "Manolo's Factory Overruns",
    "Manrique",
    "Mantequilla",
    "Manuel Casals",
    "Marange",
    "Maravilla",
    "Marca Binny's",
    "Marca Fina",
    "Marco V",
    "Marcus Daniel",
    "Mardo",
    "Maria Divina",
    "Maria Guerrero",
    "Maria Mancini",
    "Marilia & Dirceu",
    "Mario Palomino",
    "Mark IV",
    "Mark Twain",
    "Maroma",
    "Marques de Gurabo",
    "Marsh 1840",
    "Marsh Wheeling",
    "Martinez",
    "Martinez/Bazukas",
    "Master Bradley's Premium Dominican",
    "Master Roller",
    "Matacan",
    "Matador Cigars",
    "Matasa",
    "Maximo Gomez",
    "Maxim's",
    "Maxim's of Paris",
    "Maxius",
    "Maxum",
    "May Rosa",
    "Maya",
    "Maya Palma",
    "Mayorga",
    "McCranies House Brand",
    "MCW (My Cuban Wheel)",
    "MD",
    "MD (Indonesia)",
    "Meccarillos",
    "Medal Of Honor",
    "Mederos",
    "Mederos Cubanacan",
    "Medici (by Alec Bradley)",
    "Medina",
    "Memoria de Cuba",
    "Memphis Blue",
    "Mendez Y Lopez",
    "Mercedes",
    "Mexican Emperador",
    "Mexican Segundos",
    "Mi Barrio",
    "Mi Habano",
    "Mi Tierra",
    "Miami Mafia (by Cubanissimo)",
    "Miami Suites",
    "MiCubano",
    "Middleton",
    "Middleton Black & Mild",
    "Miguel Grau",
    "Miguel Private Cigars",
    "Miguel y Familia",
    "MiHabano",
    "Mike Ditka",
    "Mike's 1950",
    "Mike's Cigars",
    "Milano Cigar Collection",
    "Minotaur (by Felipe Gregario)",
    "Miraculous Templar",
    "Miramar",
    "Miranda",
    "Mister B Handmade",
    "Mister Hyde's",
    "Miura",
    "Miyares",
    "MJH",
    "MOB",
    "Mocambo",
    "Mocha",
    "Mocha Supreme",
    "Mohican",
    "Moishe Pipik",
    "Mombacho",
    "Mom's",
    "Monaco",
    "Monseñor de la Habana",
    "Monseñor de la Romana",
    "Montague",
    "Montalvo",
    "Montana Sport",
    "Monte Albar",
    "Monte Canario",
    "Monte Pascoal",
    "Monte Real",
    "Monte Verde",
    "Montebello",
    "Montecristo",
    "Montecristo (Cuban)",
    "Montecruz",
    "Montego",
    "MontePalma",
    "Monteria",
    "Montero",
    "Montes de Oca",
    "Montes de Oro",
    "Montesino",
    "Montezuma",
    "Monument",
    "Moolah",
    "Moonshine Crooks",
    "Moore & Bode",
    "Morejon y Cuesta",
    "Morgan Alexander",
    "Morocho",
    "Morro Castle",
    "Morton Collection",
    "Mosaico",
    "Most Wanted",
    "Motta",
    "Moya",
    "Mr Charutos",
    "Mr. B's",
    "Mr. Wonderful",
    "Mulberry Street Cigar Co.",
    "Mundi Victor",
    "Muniemaker",
    "Muniemaker CT Valley",
    "Murano",
    "Muriel",
    "Mursuli",
    "My Father",
    "Mya",
    "Mylo's Castle",
    "Mysterioso",
    "Mythos Solitude",
    "Nacionales W",
    "Nadi",
    "Nafilyan",
    "Napa",
    "Napa Reserve",
    "Nat Cicco's",
    "Nat Sherman",
    "National Brand",
    "Nativo",
    "Naughty Goose",
    "Navarre",
    "Navarro",
    "Navigator",
    "NEOS",
    "Neptune",
    "Nesticos (Plasencia)",
    "Nestor",
    "Nestor Miranda",
    "Nestor Plasencia",
    "New Cuba",
    "New Generation",
    "New Havana Cigars",
    "New York",
    "New York Minute",
    "Next Generation",
    "Nic Biggy",
    "Nica",
    "Nica Libre",
    "Nica' Reina",
    "Nicahabana",
    "Nicaragua Habanos",
    "Nicaraguan Cream",
    "Nicaraguan Estates",
    "Nicaraguan Gold",
    "Nicaraguan Heirloom",
    "Nicaraguan Ligero-Laced 2nds",
    "Nicaraguan Nude",
    "Nicaraguan Overruns",
    "Nicaraguan Special Selection",
    "Nicarao",
    "Nice Guys",
    "Nicole Miller",
    "Nikki",
    "Nino Vasquez",
    "Nitro",
    "Nobel",
    "Nobleza",
    "Nomad",
    "Nomi",
    "Non Plus Ultra",
    "Nostalgia",
    "Novillos (Formerly Stubs by Miura Cigars)",
    "Nudes",
    "Nuevitas",
    "NYC Cigar Co.",
    "Oak Brook Tobacco Company",
    "Oakbrook",
    "Oasis",
    "Oba! Oba! - by Perdomo",
    "Obsidian",
    "Ocaso",
    "Occidental",
    "Octavo",
    "Oh Que Bueno",
    "Oja",
    "Ojeda",
    "Ol' Times",
    "Old Fashioned",
    "Old Havana",
    "Old Henry",
    "Old Homestead",
    "Old Port",
    "Old Powder Keg",
    "Old School",
    "Old Virginia",
    "Oldies But Goodies",
    "Olganza",
    "Oliva",
    "Oliva (Angel)",
    "Oliveros",
    "Olor",
    "Olor del Cibao",
    "Olor Nicaragua",
    "Olympia",
    "Omar Ortez",
    "Omar Ortiz",
    "Omega",
    "Oneoff",
    "Onyx",
    "Optimo",
    "Opus X",
    "Orange Label",
    "Orient Express",
    "Original Cubans",
    "Origins",
    "Orinoco 1613",
    "Ornelas",
    "Oro Cubano",
    "Oro de Cuba",
    "Oro de Esteli",
    "Oro de Panama",
    "Oro de Reinitas",
    "Ortega",
    "Ortez y Turrent",
    "ORTSAC",
    "Oscar",
    "Oud Kampen",
    "Our Family's Finest",
    "Outdoorsman (Camacho)",
    "Over Production",
    "Oxford",
    "P. Bello y Cia",
    "P. Benitez",
    "P.L.",
    "Paco",
    "Padilla",
    "Padilla/Studio Tobac",
    "Padron",
    "Pai Gow",
    "Paisanos",
    "Paket Hemat",
    "Palma",
    "Palma Real",
    "Palmarejo",
    "Palmas Puro",
    "Palomino",
    "Palomitas",
    "Pan American",
    "PANA",
    "Panama Red",
    "Pancho Floods",
    "Pancho's Reserve",
    "Panorea",
    "Panter",
    "Papayo",
    "Par",
    "Para Siempre",
    "Para Ti",
    "Paradise Island",
    "Paradiso Cubano",
    "Parcel 77",
    "Parodi",
    "Partagas",
    "Partagas (Cuban)",
    "Particulares",
    "Paseana",
    "Pasha Reserve Collection",
    "Paso D'León",
    "Pastora",
    "Patoro",
    "Patriot",
    "Patriota",
    "Paul Garmirian",
    "Paul Stulac",
    "Payne-Mason",
    "Pedro Estevez",
    "Pedro Martin",
    "Peñamil",
    "Penguin",
    "Pera",
    "Perdomo",
    "Perez",
    "Perfección",
    "Perfect Cut",
    "Perfecto Garcia",
    "Pergamino",
    "Perique",
    "Perla del Mar",
    "Personales",
    "Peter Stokkebye",
    "Peterson",
    "Petri",
    "Petrus",
    "Phatash",
    "Pheasant",
    "Phil",
    "Phillies",
    "Phillipine Cigar Company",
    "Phillips & King",
    "Philosophy",
    "Picasso",
    "Pickwick",
    "Pigtail",
    "Piloto Cubano",
    "Pinar",
    "Pinar de Oro",
    "Pinar del Rio",
    "Pinnacle",
    "Pintor",
    "PIO",
    "Pioneer Valley",
    "Pipers Haven",
    "Pirata",
    "Pirate's Gold",
    "Placeres",
    "Plasencia",
    "Playboy by Altadis",
    "Playboy by Don Diego",
    "Players Club",
    "PLC",
    "Pleiades",
    "Poderozo",
    "Ponderables",
    "Pontalba",
    "Por Larranaga",
    "Por Larranaga (Cuban)",
    "Por Matamor",
    "Port Royal",
    "Porto Bello",
    "Potente",
    "Praderas",
    "Premier",
    "Premium",
    "Premium Blend Cigars",
    "Premium Cuban",
    "Premium Dominicana",
    "Premium Selection (by Kristoff)",
    "Premium Value",
    "President's Private Stock",
    "Presumidos (Thompson)",
    "Prida",
    "Pride",
    "Pride of Copan",
    "Pride of Jamaica",
    "Pride of Panama",
    "Prime Time",
    "Primera de Honduras",
    "Primera de Nicaragua",
    "Primero de Fabrica",
    "Primeros",
    "Primo de Cuba",
    "Primo del Cristo",
    "Primo del Rey",
    "Primos Oscuro Reserve",
    "Primos Oscuro Reserve Cigars",
    "Prince Albert",
    "Principes (by La Aurora)",
    "Private Stock",
    "Privateer",
    "Profesor Sila",
    "Profile by Cult",
    "Pryme",
    "Pueblo Dominicano",
    "Punch",
    "Punch (Cuban)",
    "Pura Experiencia",
    "Purisco",
    "Puritos",
    "Puritos Cossa Nostra",
    "Puro Nicaragua",
    "Puro Placer",
    "Puro Sabor",
    "Puro Venezolano",
    "Puroexpress",
    "Purofino",
    "Puros del Ibera",
    "Puros Don Abreu",
    "Puros Huerfanos",
    "Puros Indios",
    "Puros Irene",
    "Puros Morgan",
    "Puros Nirvana",
    "Puros of St James",
    "Puros Passionados",
    "Puros Polanco",
    "Puros Reales",
    "Puros Reynoso",
    "Puros Tejera",
    "Pyramid",
    "Pyro",
    "Q-ban Fuerte",
    "QE2",
    "Q'Oro",
    "QQ",
    "Quadrado",
    "Quai d'Orsay",
    "Queen City",
    "Quesada",
    "Quetzal",
    "Quintero",
    "Quintero (Cuban) (Quintero y Hermano)",
    "Quintessa",
    "Quirantes",
    "Quisqueya",
    "Quisqueyana",
    "Quo Vadimus",
    "Quorum",
    "R. A. Villamil",
    "R.G. Santiago",
    "RA",
    "Rafael",
    "Rafael Gonzalez",
    "Rafael Gonzalez (Cuban)",
    "Rafaeli's",
    "Raji's Untimely Demise",
    "Ram Rod",
    "Ramayana",
    "Rambling River",
    "Ramon Allones",
    "Ramon Allones (Cuban)",
    "Ramon Bueso",
    "Ramon y Ramon",
    "Ramondo",
    "Ramrod",
    "Rancho Dominicano",
    "Randello",
    "Randello X",
    "Rav",
    "RB Fundadores",
    "Real Cuban Knock-Offs",
    "Real Men Smoke Cigars",
    "Real Morenos",
    "Reas",
    "Recluse (Iconic Leaf Cigar Co.)",
    "Recon",
    "Red Buck",
    "Red Dot",
    "Red Head",
    "Red Lion",
    "Redencion",
    "Redlands",
    "Reel Grande",
    "Regalo",
    "Regalos",
    "Regius",
    "Reina de Manilla",
    "Reinado",
    "Relajado",
    "Remedios",
    "Remington",
    "Reo",
    "Repeater",
    "Reposado 96",
    "Republica Cigars",
    "Republica Dominican",
    "Reserva Cristobal",
    "Reserva de Inexpensivo",
    "Reserva Dorado",
    "Reserva Ligadora",
    "Reserva Limitada",
    "Reserva No. 464",
    "Reserva Presidentè",
    "Revolucion",
    "Rex Britannia",
    "Rey Alfonso",
    "Rey de Reyes",
    "Rey de Reyes (Miami Cigar Co.)",
    "Rey de Reyes (Rolando Reyes)",
    "Rey de Zaba",
    "Rey Miguel",
    "Reyes Family",
    "Reyes y Benicio",
    "Reynaldo",
    "Rhum (Ted's Cigars)",
    "Riata",
    "Rical",
    "Ricardo",
    "Richard Nixon",
    "Richards",
    "Richwood",
    "Rico Havana",
    "Ricos Dominicanos",
    "Rigoletto",
    "Rima",
    "Rio de Cuba",
    "Rio Mayos",
    "Rio Tabac",
    "Ritmeester",
    "Ritz Square",
    "Rivalo",
    "Robali",
    "Robert Burns",
    "Roberto",
    "Roble Viejo",
    "Rocco Gaetano d'Angelo",
    "Rochesterville 1831",
    "Rock-A-Feller (by International Tobacco Partners)",
    "Rocky Patel",
    "Rodrigo",
    "Rodrigo de Xerex",
    "Rodriguez & Menendez",
    "Roger Jacobi Cigars",
    "Roll Back (C&C Cigars)",
    "Roller's Choice",
    "Roller's Select",
    "Roly",
    "RoMa Craft Tobac",
    "Romana",
    "Romanticos",
    "Romeo y Julieta",
    "Romeo y Julieta (Cuban)",
    "Ron Mexico",
    "Ron's Cigars",
    "Room 101",
    "Roro Mendut",
    "Rosa Cuba",
    "Rosalones",
    "Rosario Cigars",
    "Rough Rider Sweets",
    "Roughneck",
    "Roxor",
    "Royal Barbados",
    "Royal Blunt",
    "Royal Dominicana",
    "Royal Flavor",
    "Royal Hawaiian",
    "Royal Honduras",
    "Royal Jamaica",
    "Royal Jamaica (Pre-Hurricane Gilbert)",
    "Royal Manna",
    "Royal Silk",
    "Royales",
    "Rubirosa",
    "Rum Runner",
    "Rumba",
    "Rushmore",
    "Rustico",
    "Rusty Humphries",
    "Rusty's",
    "Ruy Lopez",
    "S. Plasencia Premium",
    "S.T. Dupont",
    "Sabana",
    "Sabor Cubano (by La Tradicion Cubana)",
    "Sabor Habano",
    "Sabroso",
    "SACUBA",
    "Saint Luis Rey",
    "Saint Luis Rey (Cuban)",
    "Salute to Arms",
    "Salvador",
    "Samana",
    "San Angelo",
    "San Antonio",
    "San Bajito",
    "San Carlos",
    "San Cristobal",
    "San Cristobal de La Habana",
    "San Felice",
    "San Fernando",
    "San Juan Martinez",
    "San Luis Rey",
    "San Marco",
    "San Martin",
    "San Miguel",
    "San Miguel y Ramirez",
    "San Pedro Cubana",
    "San Vicente Collection",
    "Sancho Panza",
    "Sancho Panza (Cuban)",
    "Sancti Spiritus",
    "Sandes",
    "Sanj's Smoke Shop",
    "Santa Ana",
    "Santa Clara",
    "Santa Cruz (Canary Islands)",
    "Santa Cruz (Jamaica)",
    "Santa Damiana",
    "Santa Fe",
    "Santa Julia",
    "Santa Karina",
    "Santa Rosa",
    "Santamaria",
    "Santiago",
    "Santiago (Dominican)",
    "Santiago Cabana",
    "Santiago Cigar Factory",
    "Santiago Silk",
    "Santiana",
    "Santo Diego",
    "Sao Salvador",
    "Savannah Bulldogs",
    "Savinelli",
    "Savoy",
    "SBK (Small Batch Kings)",
    "Scarface",
    "Schimmelpenninck",
    "Schrader Hispaniola",
    "Schwartz & Fenaoui",
    "Second Growth",
    "Secret Blend of Cuba",
    "Segovia",
    "Seijas",
    "Seleccion Privada (DR)",
    "Seleccion Privada (NIC)",
    "Selecto Puro Dominicano",
    "Sello de Oro",
    "Semar",
    "Semper Fi",
    "Sencillo",
    "Seneca",
    "Señor Bonilla",
    "Señor David",
    "Señor San Andres",
    "Senor Solomon",
    "Serafin de Cuba",
    "Series X",
    "Serrano",
    "Sex on the Beach",
    "Shaggys",
    "Shakespeare",
    "Shaman",
    "Shane Old Fashioned",
    "Shangri La",
    "SHB",
    "Shrapnel",
    "Siboney",
    "Siboney (Cuban)",
    "SIG",
    "Siglo 21",
    "Siglo Limited Reserve",
    "Signature Collection",
    "Signature House Blend",
    "Signature Stogie",
    "Signet",
    "Silo Cigars",
    "Silverdale",
    "Simonoff",
    "Simpatico",
    "Sinatra",
    "Sir Vin Cigars",
    "Smok-a-Cuba",
    "Smoke Inn",
    "Smoker Friendly",
    "Smoker's Best",
    "Smokers Choice",
    "Smokin'",
    "Smokin Joes",
    "Smokin' Sandwich",
    "Smokin' Tiger",
    "Smokin' Toad",
    "Smokin' World",
    "SoEx",
    "Sol Cubano",
    "Sol de Cuba",
    "Solamente",
    "Soldado Americano",
    "Soleares",
    "Soledad",
    "Solo Aroma",
    "Solo Aroma de Esteli",
    "Solo Cafe",
    "Sombrio Deseo",
    "Sonador (Thompson)",
    "Sosa",
    "South Beach",
    "South Beach Flavors",
    "Spag & Co.",
    "Spanish Galleon",
    "Spanish Heirloom",
    "Spartacus",
    "SPC",
    "Speakeasy",
    "Special Blends by Alec Bradley",
    "Special Caribbeans",
    "Special Jamaican",
    "Sportsman's Reserve",
    "St George",
    "St. Croix",
    "Stag",
    "Steel City Cigarillos",
    "Stefano",
    "Stixx",
    "Stock 10/1",
    "Stogie Castillo",
    "Stogies on Grand",
    "Stradivarius",
    "Strelsky",
    "Sturgis",
    "Sturgis Smoke",
    "Suarez",
    "Suave",
    "Sublimes",
    "Suenos Oro",
    "Suerdieck",
    "Sultan",
    "Summus",
    "Sun Ripened Oscuros",
    "Sunrise Reserve",
    "Sunset of Key West",
    "Super Premium",
    "Super Value",
    "SuperiorCigars.com",
    "Superiores",
    "Supervisor Selection By Alec Bradley",
    "Supre Sweets",
    "Supreme Blend",
    "Surrogates",
    "Svenska Tobaksbolaget",
    "SWAG",
    "Sweet Aromas by Macabi",
    "Sweet Daddies",
    "Sweet Nostalgia",
    "Sweeteez",
    "Swigar",
    "Swisher",
    "T&P (Guatemala)",
    "T. Mercedes",
    "T.L. Johnson",
    "T.N.J. Smokin' Spirits",
    "Tabac Ramones",
    "Tabacalera",
    "Tabacalera Esteli",
    "Tabacalera y Familia",
    "Tabacales del Sur",
    "Tabacconist Choice",
    "Tabaco Ramones",
    "Tabacos Bandoleros",
    "Tabamex",
    "Tabanero",
    "Tabantillas",
    "Table 36",
    "Taboo",
    "Taino",
    "Tambo",
    "Tambor",
    "Tamboril",
    "Tampa Nugget",
    "Tampa Sweet",
    "Tampa Tobacco Company",
    "Tampa Trolleys",
    "Tampa Tropics",
    "Tarazona",
    "Tarpon Sponger",
    "Tatiana",
    "Tatuaje",
    "Tea Party Cigar",
    "Te-Amo",
    "Ted's Made By Hand (Ted's Cigars)",
    "Temple Hall",
    "Tena y Vega",
    "Tenorio",
    "Tesa Cigar Co.",
    "Tesa Colores",
    "Tesoro",
    "Tesoros Cubanos",
    "Tesshu Tobac",
    "Texana",
    "The Churchill Cigar",
    "The Cigar",
    "The Cigar Pequeno",
    "The Dominican",
    "The Don",
    "The Drake",
    "The Famous Rum Runner",
    "The Flava",
    "The Football Cigar",
    "The Good, Bad & Ugly",
    "The Original Key West Cigar Factory",
    "The Smokin` Cigar Inc.",
    "The Thin Blue Line",
    "Third Millenium",
    "Thomas Hinds",
    "Thomas Jefferson Deuces",
    "Thompson",
    "Thurman Thomas",
    "Tia Martia",
    "Tiburon",
    "Tico",
    "Tierra del Sol",
    "Tijuana Smalls",
    "Timbuctoo",
    "Timothy's Fine Tobaccos",
    "Tinder Box",
    "Tio Pepe",
    "Tiparillo",
    "TNT",
    "Tobacanary",
    "Tobacco Factory (Evan's Tobacco Factory)",
    "Tobacco Haven",
    "Tobaco Nacional",
    "Tobajara",
    "Tony Alvarez",
    "Top Cigars",
    "Top Hat",
    "Topper",
    "Topstone",
    "Torcedor",
    "Torcido",
    "Toro Bravo",
    "Toro de Oro",
    "Toro y Leon",
    "Toros",
    "Torquino",
    "Torres",
    "Tortuga",
    "Tosa",
    "Toscano",
    "Total Flame",
    "Trabuco",
    "Trader Jack's",
    "Trader's Reserve",
    "Tranquilo",
    "Tre Sigari",
    "Treasures of Costa Rica",
    "Tres Anos Dominican",
    "Tresado",
    "Trichinopoly",
    "Trinidad",
    "Trinidad (Cuban)",
    "Trinidad y Cia",
    "Trinidad y Hermano",
    "Trocadero",
    "Tropical Fever",
    "Tropical Republic",
    "Troya",
    "Troya (Cuban)",
    "Troya Clasico Limited Edition",
    "True Blunt",
    "Tueros",
    "Tulas",
    "Turei",
    "Twinkle",
    "Two-Tone",
    "Ugly Coyote",
    "Unbanded Cigars.com",
    "Uncle Sam",
    "United Cigar",
    "Urbano",
    "V Centennial (Tropical Tobacco)",
    "V. M. Santana",
    "Valencia",
    "Vallarta Cigar Factory",
    "Valle Dorado",
    "Valle Grande",
    "Vallejuelo",
    "Vamma Del Sol",
    "Van der Donk",
    "Van 't Veen",
    "Vaquero",
    "Vargas",
    "Varina Farms",
    "Vartan",
    "Vasco da Gama",
    "Vato",
    "Vega del Rey",
    "Vega del Tader",
    "Vega Fina",
    "Vega Fina (DR)",
    "Vega Fina (Sp)",
    "Vega Palmera",
    "Vega Real",
    "Vega Talanga",
    "Vegas de Fonseca",
    "Vegas de Nicaragua",
    "Vegas de Santiago",
    "Vegas de Tabacalera Esteli",
    "Vegas Robaina",
    "Vegueros",
    "Velasquez",
    "Velvet Cigars",
    "Vendetta",
    "Vengeance",
    "Venom",
    "Ventura Cigar",
    "Veracruz",
    "Verdadero",
    "Verellen",
    "Veritas",
    "Verona",
    "Verona (Egypt)",
    "Viaje",
    "Vibe",
    "Victor de La Cruz",
    "Victor Sinclair",
    "Victoria",
    "Victorino",
    "Victory",
    "Vieja Hacienda",
    "Vieja Tradicion",
    "Vigilante",
    "Viking Village",
    "Villa",
    "Villa de Cuba",
    "Villa Dominicana",
    "Villa Havana",
    "Villa Zamorano",
    "Villar y Villar",
    "Villazon Hatsa",
    "Villega Reales",
    "Villiger",
    "Vindicator",
    "Vintage Especial (by Plasencia)",
    "VIP (by George Rico)",
    "Virtuoso",
    "Vista de Cuba",
    "Viva Bandito",
    "Vivaldi",
    "VMI",
    "Vogel",
    "Voila",
    "VSOP",
    "Vudu",
    "Vuelta Abajo",
    "Vueltabajo",
    "W&D",
    "W. F. Mild (Finck)",
    "Waller & Bengtsson",
    "Warlock",
    "Warped",
    "WB Brand",
    "We The People",
    "West Indies",
    "West Indies Cigar CO",
    "Westminster",
    "What's Knot to Love",
    "White Buffalo",
    "White Cat",
    "White Horse (Felipe Gregorio)",
    "White Owl",
    "White Star",
    "Willem II",
    "William Penn",
    "William Ventura",
    "Willy Cigars",
    "Wilson Adamas",
    "Winchester",
    "Windsor",
    "Winston Churchill (Davidoff)",
    "Wintermann",
    "Wintersmokes",
    "Winthrop",
    "Wise Guys",
    "Wismilak",
    "Wm. Ascot",
    "Wolf Brothers",
    "WTF (Outlaw Cigars)",
    "WTF Cigars",
    "Wynwood",
    "Xerez",
    "Xikar",
    "Xing",
    "X-Rated",
    "XXO",
    "Y.B.",
    "Yago",
    "Yankee Clipper",
    "Yaquiba (Haiti)",
    "Ybor Cigars Plus",
    "Ybor Gold",
    "Yellow Band",
    "Ynego Montoya",
    "Yumuri",
    "Zahi",
    "Zelo de Cuba",
    "Zemis",
    "Zeus (Corona Cigar Co.)",
    "Z-Gar",
    "Zigari",
    "Zino",
    "Ziq",
    "Zoidian"];
module.exports = cigarBrands;