var domainValues = {
    "binders": ["Argentina", "Aruba", "Barbados", "Belgium", "Belize", "Brazil", "Burma", "Cameroon", "Canada", "Canary Islands", "Caribbean Basin Cuban Seed", "China", "Colombia", "Connecticut Broadleaf", "Connecticut Shade", "Connecticut", "Corojo", "Costa Rica", "Havana 98 Criollo", "Criollo", "Cuba", "Cypress", "Denmark", "Dominican Republic", "Ecuador", "France", "Germany", "Greece", "Guatemala", "Habana 2000", "Haiti", "Holland", "Homogenized Tobacco Leaf", "Honduras", "India", "Indonesia", "Italy", "Jamaica", "Java", "Korea", "Malaysia", "Mexico", "Myanmar", "Natural Tobacco Leaf", "Nepal", "Netherlands", "Nicaragua", "Panama", "Pennsylvania", "Peru", "Philippines", "Pipe Tobacco", "Puerto Rico", "Spain", "Sri Lanka", "Sumatra", "Sweden", "Switzerland", "Syria", "Turkey", "United States", "Venezuela"],
    "colors": ["Claro", "Colorado Claro", "Colorado Maduro", "Colorado", "Double Claro", "Maduro", "Multiple", "Naturale", "Oscuro", "Rosado"],
    "countries": ["Argentina", "Aruba", "Azores", "Bahamas", "Barbados", "Belgium", "Belize", "Brazil", "Burma", "Cameroon", "Canada", "Canary Islands", "China", "Colombia", "Costa Rica", "Cuba", "Cypress", "Denmark", "Dominican Republic", "Ecuador", "France", "Germany", "Greece", "Guatemala", "Haiti", "Holland", "Honduras", "India", "Indonesia", "Ireland", "Italy", "Jamaica", "Java", "Korea", "Malaysia", "Mexico", "Myanmar", "Nepal", "Netherlands", "Nicaragua", "Panama", "Peru", "Philippines", "Portugal", "Puerto Rico", "Spain", "Sri Lanka", "Sumatra", "Sweden", "Switzerland", "Syria", "Turkey", "United States", "Venezuela"],
    "fillers": ["Argentina", "Aruba", "Barbados", "Belgium", "Belize", "Brazil", "Burma", "Cameroon", "Canada", "Canary Islands", "Caribbean Basin Cuban Seed", "China", "Colombia", "Connecticut", "Connecticut Broadleaf", "Connecticut Shade", "Corojo", "Costa Rica", "Havana 98 Criollo", "Criollo", "Cuba", "Cypress", "Denmark", "Dominican Republic", "Ecuador", "France", "Germany", "Greece", "Guatemala", "Habana 2000", "Haiti", "Holland", "Homogenized Tobacco Leaf", "Honduras", "India", "Indonesia", "Italy", "Jamaica", "Java", "Korea", "Malaysia", "Mexico", "Myanmar", "Natural Tobacco Leaf", "Nepal", "Netherlands", "Nicaragua", "Panama", "Pennsylvania", "Peru", "Philippines", "Pipe Tobacco", "Puerto Rico", "Spain", "Sri Lanka", "Sumatra", "Sweden", "Switzerland", "Syria", "Turkey", "United States", "Venezuela"],
    "strengths": ["Full", "Medium", "Medium-Full", "Mild", "Mild-Medium"],
    "vitolas": ["Churchill", "Cigarillo", "Corona", "Corona Extra", "Corona Gigante", "Corona Grande", "Culebra", "Double Corona", "Figurado", "Gigante", "Long Corona", "Long Panatela", "Lonsdale", "Panatela", "Parejo", "Perfecto", "Petit Corona", "Petit Panatela", "Pyramid", "Robusto", "Robusto Gordo", "Rothschild", "Short Gordo", "Short Panatela", "Slim Panatela", "Small Panatela", "Toro", "Toro Gordo", "Torpedo"],
    "wrappers": ["Argentina", "Aruba", "Barbados", "Belgium", "Belize", "Brazil", "Burma", "Cameroon", "Canada", "Canary Islands", "Caribbean Basin Cuban Seed", "China", "Colombia", "Connecticut Broadleaf", "Connecticut Shade", "Connecticut", "Corojo", "Costa Rica", "Havana 98 Criollo", "Criollo", "Cuba", "Denmark", "Dominican Republic", "Ecuador", "France", "Germany", "Greece", "Guatemala", "Habana 2000", "Haiti", "Holland", "Homogenized Tobacco Leaf", "Honduras", "India", "Indonesia", "Italy", "Jamaica", "Java", "Korea", "Malaysia", "Mexico", "Myanmar", "Natural Tobacco Leaf", "Nepal", "Netherlands", "Nicaragua", "Panama", "Pennsylvania", "Peru", "Philippines", "Pipe Tobacco", "Puerto Rico", "Spain", "Sri Lanka", "Sumatra", "Sweden", "Switzerland", "United States", "Venezuela"]
};
module.exports = domainValues;